### ISSUE TITLE
no CUDA-capable device is detected at ../aten/src/THC/THCGeneral.cpp:47

### ISSUE THREAD

**Issue by gussmith** [Media-Smart/vedastr#14]
Hi, thank you for providing this code. 

Trying to run, but I get: 
`RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at /opt/conda/conda-bld/pytorch_1591914838379/work/aten/src/THC/THCGeneral.cpp:47`
even though I do have a CUDA-capable device and tested again by running another code.

 First I installed in a docker container, got that error. 
Then I installed native using the exact instructions. Same error.
(for some reason, I had to: 
`python -m pip install --upgrade pip`
to fix the error with pip, when installing native. Docker install gave no issues. 
```
pip --version
Traceback (most recent call last):
  File "/home/olivier/code/anaconda3/envs/vedastr/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
```
before 
`pip install -r requirements.txt`

`vedastr$ python tools/test.py configs/small_satrn.py pretrained/small-SATRN/Small-SATRN.pth `
```
2020-07-28 04:25:39,895 - INFO - Assemble, Step 1, Build Dataset
2020-07-28 04:25:39,897 - INFO - current dataset length is 287 in ./data/data_lmdb_release/evaluation/CUTE80
2020-07-28 04:25:39,900 - INFO - current dataset length is 867 in ./data/data_lmdb_release/evaluation/IC03_867
2020-07-28 04:25:39,904 - INFO - current dataset length is 1015 in ./data/data_lmdb_release/evaluation/IC13_1015
2020-07-28 04:25:39,911 - INFO - current dataset length is 1922 in ./data/data_lmdb_release/evaluation/IC15_2077
2020-07-28 04:25:39,921 - INFO - current dataset length is 3000 in ./data/data_lmdb_release/evaluation/IIIT5k_3000
2020-07-28 04:25:39,924 - INFO - current dataset length is 647 in ./data/data_lmdb_release/evaluation/SVT
2020-07-28 04:25:39,927 - INFO - current dataset length is 645 in ./data/data_lmdb_release/evaluation/SVTP
2020-07-28 04:25:39,927 - INFO - Assemble, Step 2, Build Dataloader
2020-07-28 04:25:39,927 - INFO - Assemble, Step 3, Build Model
2020-07-28 04:25:39,951 - INFO - GResNet init weights
2020-07-28 04:25:40,271 - INFO - TransformerEncoder init weights
2020-07-28 04:25:40,761 - INFO - TransformerDecoder init weights
2020-07-28 04:25:40,858 - INFO - TransformerHead init weights
2020-07-28 04:25:40,958 - INFO - Using CPU
2020-07-28 04:25:40,958 - INFO - Assemble, Step4, Build Converter
2020-07-28 04:25:40,958 - INFO - Assemble, Step 5, Build Criterion
2020-07-28 04:25:40,959 - INFO - Assemble, Step 6, Build Optimizer
2020-07-28 04:25:40,960 - INFO - Assemble, Step 7, Build LR scheduler
2020-07-28 04:25:40,960 - INFO - Assemble, Step 8, Build Runner
THCudaCheck FAIL file=../aten/src/THC/THCGeneral.cpp line=47 error=100 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "tools/test.py", line 28, in <module>
    main()
  File "tools/test.py", line 23, in main
    runner = assemble(cfg_fp, test_mode=True, checkpoint=checkpoint)
  File "/home/olivier/projects/code/vedastr/tools/../../vedastr/vedastr/assembler/assembler.py", line 130, in assemble
    runner.resume(**cfg['resume'])
  File "/home/olivier/projects/code/vedastr/tools/../../vedastr/vedastr/runner/runner.py", line 256, in resume
    device_id = torch.cuda.current_device()
  File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 375, in current_device
    _lazy_init()
  File "/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 195, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at ../aten/src/THC/THCGeneral.cpp:47

```
I noticed the: 
`2020-07-28 04:25:40,958 - INFO - Using CPU`

I welcome your suggestion. I have not found an answer in my web search.

**Comment by ChaseMonsterAway** [comment]
What's the result of ``torch.cuda.is_avalable()`` in your environment?

**Comment by ChaseMonsterAway** [comment]
what is the gpu_id in the config file?
>https://github.com/Media-Smart/vedastr/blob/b369b40512f5644f71bdd47db61e80d480c9f7d5/configs/resnet_fc.py#L199

**Comment by gussmith** [comment]
Yep, thank you. I had forgotten to look into the configs directory for the small_satrn.py file
I just had it running by replacing in assembler.py: 
`    os.environ['CUDA_VISIBLE_DEVICES'] = '0' # cfg['gpu_id']`
but changing the config file is cleaner! 
Thank you and thanks for your swift reply! Best.

**Comment by ChaseMonsterAway** [comment]
You are welcome.
