### ISSUE TITLE
Small SATRN not learning during training

### ISSUE THREAD

**Issue by ala38** [Media-Smart/vedastr#17]
I have been attempting to train the Small SATRN model using the MJSynthetic Data Set, and the model has not reduced loss at all after 100000 training steps.  The loss at that point in the training is still at 4.9.  I am using the default configuration in the configs/small_SATRN.py.  I modified the file by only changing the batch size to 48 due to the memory constraints of my GPU. During training, in the messages printed to the screen, I get following message. The fact that LR is [0.0] makes me believe that perhaps the optimizer is not set up properly. 

 2020-07-31 12:36:26,344 - INFO - Train, Epoch 1, Iter 1050, LR [0.0], Loss 5.1837, acc 0.0002, edit_distance 0.011724307286992782
2020-07-31 12:36:26,344 - INFO - 
--------------------------------------------------------------------------------
Ground Truth              | Prediction                | Confidence Score & T/F
--------------------------------------------------------------------------------
maligned                  |                           | 0.0000  False
IRONICAL                  | */ay0X                    | 0.0000  False
elegies                   |                           | 0.0000  False
ANCILLARY                 | *                         | 0.1286  False
Suppurates                | l                         | 0.0840  False
--------------------------------------------------------------------------------
2020-07-31 12:36:44,811 - INFO - Train, Epoch 1, Iter 1100, LR [0.0], Loss 5.1059, acc 0.0002, edit_distance 0.01171760838729902
2020-07-31 12:36:44,811 - INFO - 
--------------------------------------------------------------------------------
Ground Truth              | Prediction                | Confidence Score & T/F
--------------------------------------------------------------------------------
MARSEILLAISE              |                           | 0.0000  False
EYEWASH                   | !7l0*                     | 0.0000  False
xx                        |                           | 0.0000  False
beautifies                | a                         | 0.1275  False
ACCREDITING               |                           | 0.0000  False

I am quite sure that I have done everything properly, because I have also been running the resnet_fc.py model using the same data set and it is training well, with loss decreasing as one would expect.

**Comment by ChaseMonsterAway** [comment]
I have fixed it yesterday. I'm sorry for late reply.

**Comment by vardhanaleti** [comment]
Hey! I didn't open an issue because the one I'm facing right now is with small SATRN. 
I have trained the tps_resenet model on a custom dataset. But I'm not able to train small satrn on the same dataset. I'm sure I've changed the config files appropriately. 

Here is the error:
2021-04-20 16:38:40,779 - INFO - Use GPU 0,1,2,3
2021-04-20 16:38:40,779 - INFO - Set cudnn deterministic True
2021-04-20 16:38:40,779 - INFO - Set cudnn benchmark True
2021-04-20 16:38:40,779 - INFO - Set seed 1111
2021-04-20 16:38:40,780 - INFO - Build model
2021-04-20 16:38:40,785 - INFO - GResNet init weights
2021-04-20 16:38:41,130 - INFO - TransformerEncoder init weights
2021-04-20 16:38:41,552 - INFO - TransformerDecoder init weights
2021-04-20 16:38:41,581 - INFO - TransformerHead init weights
Traceback (most recent call last):
  File "tools/train.py", line 42, in <module>
    main()
  File "tools/train.py", line 37, in main
    runner = TrainRunner(train_cfg, deploy_cfg, common_cfg)
  File "tools/../vedastr/runners/train_runner.py", line 19, in __init__
    train_cfg['data']['train'])
  File "tools/../vedastr/runners/base.py", line 83, in _build_dataloader
    transform = build_transform(cfg['transform'])
  File "tools/../vedastr/transforms/builder.py", line 11, in build_transform
    tf = build_from_cfg(cfg, TRANSFORMS)
  File "tools/../vedastr/utils/common.py", line 14, in build_from_cfg
    return obj_from_dict_registry(cfg, parent, default_args)
  File "tools/../vedastr/utils/common.py", line 79, in obj_from_dict_registry
    return obj_cls(**args)
  File "tools/../vedastr/transforms/transforms.py", line 192, in __init__
    super(ExpandRotate, self).__init__(**kwargs)
  File "tools/../vedastr/transforms/transforms.py", line 185, in __init__
    value=value, always_apply=always_apply, p=p)
TypeError: __init__() got an unexpected keyword argument 'value'

**Comment by vardhanaleti** [comment]
Hey,
I'm facing a similar issue. Small satrn isn't converging. 
![image](https://user-images.githubusercontent.com/55653629/118319188-0ef96500-b518-11eb-9845-2a9349697ec7.png)

I'm running both the models on the same dataset. 



2021-05-14 18:53:06,015 - INFO - Train, Epoch 20, Iter 5000, LR [5.90673314195311e-05], Loss 1.7907, acc 0.0078, edit_distance 0.30127418154761904
2021-05-14 18:53:06,038 - INFO - 
--------------------------------------------------------------------------------
Ground Truth              | Prediction                | Confidence Score & T/F
--------------------------------------------------------------------------------
रे                        | रूल                       | 0.0269	False
साथ                       |                           | 0.0000	False
मार्ग                     |                           | 0.0000	False
डंक                       |                           | 0.0000	False
विलक्षण                   | पिभा्ष्                   | 0.0016	False


Even after 5000 iterations, the loss is stuck around 1.7-1.8

**Comment by ildarkin836** [comment]
> Hey, I'm facing a similar issue. Small satrn isn't converging. ![image](https://user-images.githubusercontent.com/55653629/118319188-0ef96500-b518-11eb-9845-2a9349697ec7.png)
> 
> I'm running both the models on the same dataset.
> 
> ## 2021-05-14 18:53:06,015 - INFO - Train, Epoch 20, Iter 5000, LR [5.90673314195311e-05], Loss 1.7907, acc 0.0078, edit_distance 0.30127418154761904
> 2021-05-14 18:53:06,038 - INFO -
> ## Ground Truth | Prediction | Confidence Score & T/F
> रे | रूल | 0.0269 False साथ | | 0.0000 False मार्ग | | 0.0000 False डंक | | 0.0000 False विलक्षण | पिभा्ष् | 0.0016 False
> 
> Even after 5000 iterations, the loss is stuck around 1.7-1.8

Hi, you solved this problem?

**Comment by vardhanaleti** [comment]
> Hi, you solved this problem?

Hey, I haven't solved it.
