### ISSUE TITLE
issue when trianing my own data

### ISSUE THREAD

**Issue by HongBo713** [Media-Smart/vedastr#66]
Thank you for your awesome work! I'm recently training the cstr.py with my own datasets. I got 1 GPU with 12G memory. Do I have to use four GPU to train the cstr.py properly? Also, I got the error message "RuntimeError: The size of tensor a (24) must match the size of tensor b (7) at non0singleton dimension 3". What might cause it? The size of the image?

**Comment by ChaseMonsterAway** [comment]
Hi,
Did you use the default config file to train your own data?
 Firstly, you should change the gpu_id in cnofig file to the  gpu id you used. Then change the batch_size in the config file which represents the total batch size rather than batch size per gpu.

Can you show me the explicit erro information and where you have modified the config file?

**Comment by HongBo713** [comment]
Hi,
Thank you for your reply! I did not use the default config file to train my data. 
I modified following in the config flie:
- size of the input image and the batch_size
- GPU id
- each of the data path 

and I ran the command:
_bash tools/dist_train.sh configs/cstr.py 1_

then I got the error:
Traceback (most recent call last):
  File "tools/train.py", line 49, in <module>
    main()
  File "tools/train.py", line 45, in main
    runner()
  File "tools/../vedastr/runners/train_runner.py", line 166, in __call__
    self._train_batch(img, label)
  File "tools/../vedastr/runners/train_runner.py", line 116, in _train_batch
    pred = self.model((img,))
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "tools/../vedastr/models/model.py", line 26, in forward
    x = self.body(inputs[0])
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "tools/../vedastr/models/bodies/body.py", line 37, in forward
    out = component(inp)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "tools/../vedastr/models/bodies/component.py", line 20, in forward
    return self.component(x)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "tools/../vedastr/models/bodies/feature_extractors/decoders/gfpn.py", line 45, in forward
    x = layer(td, ll)
  File "/root/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "tools/../vedastr/models/bodies/feature_extractors/decoders/bricks/bricks.py", line 69, in forward
    feat = top_down + lateral
RuntimeError: The size of tensor a (24) must match the size of tensor b (7) at non-singleton dimension 3
Killing subprocess 2578

**Comment by ChaseMonsterAway** [comment]
You should modify the size in FPN based on your input size.

**Comment by HongBo713** [comment]
Got it! Thanks!

**Comment by bharatsubedi** [comment]
@HongBo713 could you please let me know which part of code I have to change for training my own dataset?
Please share your cstr.py and data structure if possible. 

Thank you

**Comment by HongBo713** [comment]
> @HongBo713 could you please let me know which part of code I have to change for training my own dataset?
> Please share your cstr.py and data structure if possible.
> 
> Thank you

Hi, 

I don't know if it is correct, but i modified under `decoder=dict(type='GFPN',` part (around line 110) according to my input size.
